title: Taylor W. Killian
description: > # this means to ignore newlines until "baseurl:"
  Personal research webiste for Taylor W. Killian
permalink: ':title/'
baseurl: # the subpath of your site, e.g. /blog
url: "https://twkillian.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "https://twitter.com/tw_killian" #if your site has a twitter account, enter it here

# Author Settings
author: Taylor W. Killian # add your name
author-img: TKillian_Headshot.jpg # add your photo
about-author: Senior Research Scientist # add description
twitter: tw_killian # add your Twitter handle
github: twkillian # add your Github handle
googlescholar: xA3RcaUAAAAJ&hl=en #Google Scholar
linkedin: taylor-w-killian # add your Linkedin handle
email: twkillian@gmail.com # add your Email address

# Disqus (disabled)
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
future: true
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed

paginate: 8
paginate_path: "/page/:num"

# Collections
collections:
  research:
    output: true
    permalink: /research/:title/
  teaching:
    output: true
    permalink: /teaching/:title/

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
